# Generated by Django 4.1.13 on 2024-08-27 16:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('project_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('project', models.CharField(max_length=255)),
                ('issue_type', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('in dev', 'IN DEV'), ('closed', 'CLOSED'), ('in qa', 'IN QA'), ('dev qa', 'DEV QA'), ('to do', 'TO DO'), ('dev qa approved', 'DEV QA APPROVED')], max_length=20)),
                ('summary', models.TextField()),
                ('environment', models.CharField(max_length=10)),
                ('priority', models.CharField(choices=[('high', 'HIGH'), ('low', 'LOW'), ('critical', 'CRITICAL')], max_length=10)),
                ('requirements_needed', models.BooleanField(default=False)),
                ('production_blocker', models.BooleanField(default=False)),
                ('focus_area', models.CharField(choices=[('frontend', 'FRONTEND'), ('backend', 'BACKEND'), ('database', 'DATABASE')], max_length=20)),
                ('os', models.CharField(max_length=20)),
                ('due_date', models.DateField()),
                ('story_points', models.IntegerField()),
                ('description', models.TextField()),
                ('fix_version', models.CharField(max_length=50)),
                ('labels', models.CharField(max_length=20)),
                ('attachments', models.ImageField(upload_to='tasks/')),
                ('affects_version', djongo.models.fields.JSONField()),
                ('linked_issues', djongo.models.fields.JSONField()),
                ('epic_link', models.CharField(max_length=100)),
                ('parent', models.CharField(max_length=50)),
                ('found_in_version', models.CharField(max_length=50)),
                ('components', models.CharField(max_length=50)),
                ('sprint', models.CharField(max_length=50)),
                ('release_name', models.CharField(max_length=50)),
                ('severity', models.CharField(choices=[('low', 'LOW'), ('high', 'HIGH'), ('medium', 'MEDIUM'), ('critical', 'CRITICAL')], max_length=10)),
                ('everyone_involved', djongo.models.fields.JSONField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_assigned_to', to=settings.AUTH_USER_MODEL)),
                ('assignee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_created_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
